export type CmsSection = {
  id: string
  section_type: string
  title: string
  subtitle?: string | null
  content: Record<string, any>
  settings?: Record<string, any>
  sort_order: number
  is_visible: boolean
}

export const fallbackSections: CmsSection[] = [
  {id:'banner',section_type:'banner',title:'Banner',sort_order:1,is_visible:true,content:{eyebrow:'Madhu Jayanti International Pvt Ltd',headline:'Nobody knows tea better!',cta_label:'Explore MJIPL',cta_url:'https://www.jaytea.com/about-us',overlay:'35'}},
  {id:'company_header',section_type:'company_header',title:'Madhu Jayanti International Pvt Ltd',sort_order:2,is_visible:true,content:{company_name:'Madhu Jayanti International Pvt Ltd (MJIPL)',tagline:'Tea innovation since 1942',founded:'1942',headquarters:'Kolkata, West Bengal, India',employee_count:'Global tea business',website:'https://www.jaytea.com/'}},
  {id:'about',section_type:'about',title:'About MJIPL',sort_order:3,is_visible:true,content:{statement:'Selling tea since 1942',body:'MJIPL has built a global tea business around sourcing, blending, packaging, innovation and responsible growth.',stats:[{value:'1000+',label:'Tea varieties'},{value:'4',label:'Factories'},{value:'15 million',label:'Cups a day'},{value:'42',label:'Countries served'}]}},
  {id:'leaders',section_type:'leaders',title:'Our Leaders',sort_order:4,is_visible:true,content:{intro:'Meet the people helping shape the next chapter of MJIPL.',items:[]}},
  {id:'benefits',section_type:'benefits',title:'Perks & Benefits',sort_order:5,is_visible:true,content:{items:[{icon:'♥',title:'Employee Wellbeing',description:'Add your wellbeing programmes, insurance and support policies from admin.'},{icon:'↗',title:'Learning & Growth',description:'Add development programmes, learning support and career opportunities.'},{icon:'◎',title:'Rewards & Recognition',description:'Add your compensation, recognition and employee benefit information.'}]}},
  {id:'chro',section_type:'chro',title:'Message from CHRO',sort_order:6,is_visible:true,content:{name:'CHRO',designation:'Chief Human Resources Officer',message:'Use the admin panel to add the CHRO message, photograph and optional link.'}},
  {id:'dei',section_type:'dei',title:'Inclusion, Equity and Diversity at MJIPL',sort_order:7,is_visible:true,content:{headline:'Building an environment where people can thrive',body:'Add MJIPL’s inclusion, equity and diversity commitments here from the admin panel.'}},
  {id:'sustainability',section_type:'sustainability',title:'Sustainability',sort_order:8,is_visible:true,content:{headline:'Committed to responsible growth',body:'MJIPL states that it aims to produce tea sustainably by combining environmental, social and ethical principles.',stats:[{value:'62%',label:'Raw materials from sustainability-committed estates'},{value:'44%',label:'Raw materials from organic tea estates'},{value:'18,000 kWh/day',label:'Clean energy generated by windmills'}],cta_label:'Our Sustainability Story',cta_url:'https://www.jaytea.com/sustainability-story'}},
  {id:'csr',section_type:'csr',title:'Corporate Social Responsibility',sort_order:9,is_visible:true,content:{intro:'Showcase MJIPL’s community programmes, education, livelihood, health and environmental initiatives.',items:[]}},
  {id:'awards',section_type:'awards',title:'Our Awards & Recognitions',sort_order:10,is_visible:true,content:{items:[]}},
  {id:'achievements',section_type:'achievements',title:'MJIPL Achievements',sort_order:11,is_visible:true,content:{items:[{value:'80+ years',title:'Tea heritage',description:'A long-standing tea business with global operations.'},{value:'1000+',title:'Varieties',description:'Black, green, white, herbal and naturally flavoured teas.'},{value:'4',title:'Factories',description:'Integrated manufacturing footprint.'},{value:'42',title:'Countries',description:'Tea served across global markets.'}]}},
  {id:'life',section_type:'life',title:'Life at MJIPL',sort_order:12,is_visible:true,content:{intro:'Share people stories, workplaces, celebrations, learning and life across MJIPL.',items:[]}},
  {id:'reviews',section_type:'reviews',title:'MJIPL Reviews',sort_order:13,is_visible:true,content:{rating:'0.0',review_count:'0',items:[]}},
  {id:'creche',section_type:'creche',title:'Creche Facility at MJIPL',sort_order:14,is_visible:true,content:{body:'Add details, images and policies for childcare and parent support here.'}},
  {id:'communities',section_type:'communities',title:'Transforming Communities across India',sort_order:15,is_visible:true,content:{body:'Add MJIPL community projects and their locations here.',items:[]}},
  {id:'jobs',section_type:'jobs',title:'MJIPL Job Openings',sort_order:16,is_visible:true,content:{intro:'Join the world of tea innovation.',items:[]}},
  {id:'locations',section_type:'locations',title:'MJIPL Office Locations',sort_order:17,is_visible:true,content:{items:[{office_name:'Corporate Office',city:'Kolkata',state:'West Bengal',country:'India',address:'Bio-Wonder, 15th Floor, 789, Anandapur Main Road, Kolkata 700107',phone:'+91 33 6657 4100',email:'info@jaytea.com'}]}},
  {id:'connect',section_type:'connect',title:'Connect with us',sort_order:18,is_visible:true,content:{website:'https://www.jaytea.com/',email:'info@jaytea.com',phone:'+91 33 6657 4100',socials:[]}},
  {id:'faqs',section_type:'faqs',title:'MJIPL FAQs',sort_order:19,is_visible:true,content:{items:[{question:'When was MJIPL founded?',answer:'MJIPL has been selling tea since 1942.'},{question:'Where is MJIPL headquartered?',answer:'MJIPL is headquartered in Kolkata, West Bengal, India.'},{question:'How can I explore careers at MJIPL?',answer:'Visit the MJIPL careers page or use the job openings section above.'}]}}
]
